# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20170313_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='relatives',
            field=models.ManyToManyField(to='person.Person'),
        ),
    ]
